import Navigation from "components/nav";
import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>JamStack - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
    </div>
  );
};
export default Home;
